import React, { useState, useEffect } from 'react';
import { History, Search, AlertTriangle } from 'lucide-react';

interface AuditRecord {
  audit_id: string;
  event_id: string;
  action: string;
  actor: string;
  timestamp: string;
  status: string;
  description: string;
}

export const AuditTrailPage: React.FC = () => {
  const [logs, setLogs] = useState<AuditRecord[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  // Search and Filter States
  const [searchEventId, setSearchEventId] = useState<string>('');
  const [actionFilter, setActionFilter] = useState<string>('all');
  const [statusFilter, setStatusFilter] = useState<string>('all');

  useEffect(() => {
    let active = true;
    const fetchAudits = async () => {
      try {
        // Construct query parameters
        const params = new URLSearchParams();
        if (searchEventId.trim()) params.append('event_id', searchEventId.trim().toUpperCase());
        if (actionFilter !== 'all') params.append('action', actionFilter);
        if (statusFilter !== 'all') params.append('status', statusFilter);

        const response = await fetch(`http://localhost:8000/api/audit?${params.toString()}`);
        if (!response.ok) {
          throw new Error('Failed to load system audit trail logs.');
        }
        const data = await response.json();
        if (active) {
          setLogs(data);
          setLoading(false);
        }
      } catch (err: any) {
        if (active) {
          setError(err.message || 'Unknown network error');
          setLoading(false);
        }
      }
    };

    const delayDebounce = setTimeout(() => {
      fetchAudits();
    }, 300); // 300ms debounce for typing event ID searches

    return () => {
      clearTimeout(delayDebounce);
      active = false;
    };
  }, [searchEventId, actionFilter, statusFilter]);

  if (loading && logs.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center h-96 space-y-4">
        <div className="w-10 h-10 border-4 border-brandActive border-t-transparent rounded-full animate-spin" />
        <span className="text-secondaryText text-sm font-semibold">Loading system audit trail...</span>
      </div>
    );
  }

  if (error) {
    return (
      <div className="bg-red-50 border border-red-200 rounded-3xl p-6 flex items-start gap-4 max-w-2xl mx-auto my-12">
        <AlertTriangle className="w-6 h-6 text-red-500 shrink-0 mt-0.5" />
        <div>
          <h3 className="font-extrabold text-red-800 text-lg">Failed to Load Logs</h3>
          <p className="text-red-700 text-sm mt-1 leading-relaxed">{error}</p>
          <button 
            onClick={() => window.location.reload()}
            className="mt-4 px-4 py-2 bg-red-100 text-red-800 font-bold text-xs rounded-xl hover:bg-red-200 transition-colors"
          >
            Retry Connection
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-8 animate-fade-slide-up">
      {/* Title Header */}
      <div>
        <h1 className="text-3xl font-extrabold text-primaryText tracking-tight font-sans">
          Audit Trail
        </h1>
        <p className="text-secondaryText text-sm mt-1.5 font-medium">
          Comprehensive, immutable chronological system actions log generated by System and AI agents.
        </p>
      </div>

      {/* Filters Card */}
      <div className="bg-white rounded-4xl p-6 shadow-card border border-slate-100/30 flex flex-wrap gap-4 items-center justify-between">
        <div className="flex items-center gap-2 text-primaryText font-bold text-sm">
          <History className="w-4 h-4 text-brandActive" />
          Filter Logs
        </div>
        
        <div className="flex flex-wrap items-center gap-4 w-full md:w-auto">
          {/* Event ID search input */}
          <div className="relative w-full md:w-48">
            <input 
              type="text" 
              placeholder="Search Event ID..." 
              value={searchEventId}
              onChange={(e) => setSearchEventId(e.target.value)}
              className="w-full bg-slate-50 border border-slate-150 rounded-xl py-2 pl-9 pr-4 text-xs text-primaryText placeholder-secondaryText/70 focus:outline-none focus:border-brandActive"
            />
            <Search className="w-3.5 h-3.5 text-secondaryText absolute left-3 top-1/2 -translate-y-1/2" />
          </div>

          <select 
            value={actionFilter} 
            onChange={(e) => setActionFilter(e.target.value)}
            className="text-xs font-semibold text-slate-700 bg-slate-50 border border-slate-150 rounded-xl px-3 py-2 focus:outline-none focus:border-brandActive"
          >
            <option value="all">All Actions</option>
            <option value="event_detected">Event Detected</option>
            <option value="diagnosis_generated">Diagnosis Generated</option>
            <option value="decision_created">Decision Created</option>
            <option value="execution_simulated">Execution Simulated</option>
          </select>

          <select 
            value={statusFilter} 
            onChange={(e) => setStatusFilter(e.target.value)}
            className="text-xs font-semibold text-slate-700 bg-slate-50 border border-slate-150 rounded-xl px-3 py-2 focus:outline-none focus:border-brandActive"
          >
            <option value="all">All Statuses</option>
            <option value="success">Success</option>
            <option value="failed">Failed</option>
            <option value="skipped">Skipped</option>
            <option value="blocked">Blocked</option>
          </select>
        </div>
      </div>

      {/* Audit List Table */}
      <div className="bg-white rounded-4xl shadow-card border border-slate-100/30 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-slate-50 border-b border-slate-100 text-[11px] font-bold text-secondaryText uppercase tracking-wider">
                <th className="py-4 px-6 w-28">Audit ID</th>
                <th className="py-4 px-6 w-32">Event ID</th>
                <th className="py-4 px-6 w-40">Timestamp</th>
                <th className="py-4 px-6 w-44">Action</th>
                <th className="py-4 px-6 w-44">Actor</th>
                <th className="py-4 px-6 w-28">Status</th>
                <th className="py-4 px-6">Description</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 text-[13px] font-medium text-slate-700">
              {logs.length === 0 ? (
                <tr>
                  <td colSpan={7} className="text-center py-12 text-secondaryText text-sm font-semibold">
                    No matching audit records found.
                  </td>
                </tr>
              ) : (
                logs.map((r) => (
                  <tr key={r.audit_id} className="hover:bg-slate-50/50 transition-colors duration-150">
                    <td className="py-4 px-6 font-bold text-primaryText">{r.audit_id}</td>
                    <td className="py-4 px-6 font-semibold text-slate-600">{r.event_id}</td>
                    <td className="py-4 px-6 text-secondaryText">
                      {new Date(r.timestamp).toLocaleString('en-IN', { dateStyle: 'short', timeStyle: 'short' })}
                    </td>
                    <td className="py-4 px-6 capitalize">
                      <span className="bg-slate-100/70 text-slate-700 px-2 py-0.5 rounded-md text-[10px] font-bold">
                        {r.action.replace('_', ' ')}
                      </span>
                    </td>
                    <td className="py-4 px-6 text-secondaryText/90 font-semibold">{r.actor}</td>
                    <td className="py-4 px-6">
                      <span className={`px-2 py-0.5 rounded-md text-[10px] font-bold uppercase tracking-wider
                        ${r.status === 'success' ? 'bg-emerald-50 text-emerald-600' : ''}
                        ${r.status === 'failed' ? 'bg-rose-50 text-rose-600' : ''}
                        ${r.status === 'skipped' ? 'bg-slate-100 text-slate-500' : ''}
                        ${r.status === 'blocked' ? 'bg-indigo-50 text-indigo-600' : ''}
                      `}>
                        {r.status}
                      </span>
                    </td>
                    <td className="py-4 px-6 text-slate-650 leading-relaxed font-medium">{r.description}</td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
